// Class that generates test data in various languages
// At the base level, a test case is:
// - preconditions (optional)
// - input
// - expected behavior (various forms, either hardcoded vectors or a placeholder "throw" with a comment)

type TestCase = {
  preconditions?: any
  input: any
  outputConditions: any
}

const MESSAGE_TEST_CASES = {
  // Identity tests - upon new identity creation what are we expecting?
  identityCreation: {
    // Wallet private key in hex
    preconditions: {
      walletPrivateKey: '"0x00"',
    },
    input: {},
    outputConditions: {
      privateKeyBundleV1: {
        address: '"0x0000"',
        throwComment_identityKeyIsValidSecp256k1:
          'Check that the identity key is a valid secp256k1 private key',
        throwComment_checkIdentityKeySignedByWallet:
          'Check that the identity key is signed by the wallet private key',
      },
    },
  },
}

// Language generators
// - TypeScript
// - Rust
// - Swift
// - Kotlin
// - Dart (low priority)

class TypeScriptGenerator {
  testCases: any

  constructor(testCases: any) {
    this.testCases = testCases
  }

  // Generate follows the pattern:
  // - Wrap the entire thing in a function with test[testName]
  // - Preconditions become a section that has a failing assert with the preconditions listed as comments
  // - Input becomes a section that has a failing assert with the input listed as comments
  // - Output becomes a section that has a failing assert with the output listed as comments
  //   - The only difference is 'throwComment_*' keys become comments, but the rest are commented asserts
  //   so ['address', '0x00'] becomes "// assert.equal(address, '0x00')"
  generateTestCaseCode(testName: string, testCase: TestCase) {
    const preconditions = testCase.preconditions
    const input = testCase.input
    const outputConditions = testCase.outputConditions

    let code = ''
    code += `test['${testName}'] = async function() {\n`
    if (preconditions) {
      code += `  // Preconditions:\n`
      for (let [key, value] of Object.entries(preconditions)) {
        code += `  const ${key} = ${value}\n`
      }
    } else {
      code += `  // No preconditions\n`
    }
    code += '\n\n'
    if (input) {
      code += `  // Inputs:\n`
      for (let [key, value] of Object.entries(input)) {
        code += `  // ${key}: ${value}\n`
      }
    } else {
      code += `  // No input\n`
    }
    code += '\n\n'
    code += `  // Expected outputs:\n`
    for (let [outputKey, expectedOutputFields] of Object.entries(
      outputConditions
    )) {
      // Add section comment like "// Testing output: outputKey"
      code += `  // Testing output object: ${outputKey}\n`
      // Add a failing assert or comment for each key/value pair
      for (let [key, value] of Object.entries(expectedOutputFields as any)) {
        if (key.startsWith('throwComment_')) {
          code += `  // ${value}\n`
        } else {
          code += `  assert.equal(${key}, ${value})\n`
        }
      }
    }
    code += `}\n`
    return code
  }

  generate() {
    let code = ''
    // Add comment at top with the generator version
    code += `// Generated by test_generator_v2.ts\n`
    for (let [testName, test] of Object.entries(this.testCases)) {
      code += this.generateTestCaseCode(testName, test as TestCase)
    }
    return code
  }
}

export function main() {
  const generator = new TypeScriptGenerator(MESSAGE_TEST_CASES)
  console.log(generator.generate())
}

main()
